### ISSUE TITLE
ModuleNotFoundError: No module named 'agents.real_data'

### ISSUE THREAD

**Issue by aysebilginn** [jidiai/TaxAI#2]
Hello. I'm trying to redo this project as a homework for my computer science course.  I cloned the repo and tried to run the main.py file, however I do get an error: 
```
from agents.real_data.real_data import real_agent
ModuleNotFoundError: No module named 'agents.real_data'
```

I haven't seen any module named real_data in agents file. 
I'm not quite experienced with ml, so I may be wrong and be missing something.

Any help would be appreciated. Thanks.

**Comment by Miracle1207** [comment]
Sorry, it's my mistake. real_data_agent is a new AI for my upcoming project, and I accidentally imported it into this current project. I have already updated the code. You can try it again, or simply comment out the real_data.

**Comment by aysebilginn** [comment]
> Sorry, it's my mistake. real_data_agent is a new AI for my upcoming project, and I accidentally imported it into this current project. I have already updated the code. You can try it again, or simply comment out the real_data.

Thank you. And one more thing since I wanna be sure: the data source you use in main.py in other words in training part is the "advanced_scfp2022.csv" file, right and there is no other data source I need?

**Comment by Miracle1207** [comment]
> > Sorry, it's my mistake. real_data_agent is a new AI for my upcoming project, and I accidentally imported it into this current project. I have already updated the code. You can try it again, or simply comment out the real_data.
> 
> Thank you. And one more thing since I wanna be sure: the data source you use in main.py in other words in training part is the "advanced_scfp2022.csv" file, right and there is no other data source I need?

Yes! We have update the data as "advanced_scfp2022.csv", instead of SCF2013
